// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vitalis.Data;

#nullable disable

namespace Vitalis.Data.Migrations
{
    [DbContext(typeof(VitalisDbContext))]
    [Migration("20260419200250_Seeded")]
    partial class Seeded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IngredientTag", b =>
                {
                    b.Property<int>("IngredientsId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("IngredientsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("IngredientTag");

                    b.HasData(
                        new
                        {
                            IngredientsId = 1,
                            TagsId = 1
                        },
                        new
                        {
                            IngredientsId = 1,
                            TagsId = 8
                        },
                        new
                        {
                            IngredientsId = 1,
                            TagsId = 9
                        },
                        new
                        {
                            IngredientsId = 2,
                            TagsId = 2
                        },
                        new
                        {
                            IngredientsId = 2,
                            TagsId = 7
                        },
                        new
                        {
                            IngredientsId = 2,
                            TagsId = 8
                        },
                        new
                        {
                            IngredientsId = 3,
                            TagsId = 4
                        },
                        new
                        {
                            IngredientsId = 3,
                            TagsId = 8
                        },
                        new
                        {
                            IngredientsId = 4,
                            TagsId = 3
                        },
                        new
                        {
                            IngredientsId = 4,
                            TagsId = 8
                        },
                        new
                        {
                            IngredientsId = 5,
                            TagsId = 1
                        },
                        new
                        {
                            IngredientsId = 5,
                            TagsId = 3
                        },
                        new
                        {
                            IngredientsId = 6,
                            TagsId = 1
                        },
                        new
                        {
                            IngredientsId = 6,
                            TagsId = 3
                        },
                        new
                        {
                            IngredientsId = 6,
                            TagsId = 8
                        },
                        new
                        {
                            IngredientsId = 7,
                            TagsId = 2
                        },
                        new
                        {
                            IngredientsId = 7,
                            TagsId = 4
                        },
                        new
                        {
                            IngredientsId = 8,
                            TagsId = 4
                        },
                        new
                        {
                            IngredientsId = 8,
                            TagsId = 8
                        },
                        new
                        {
                            IngredientsId = 9,
                            TagsId = 1
                        },
                        new
                        {
                            IngredientsId = 9,
                            TagsId = 6
                        },
                        new
                        {
                            IngredientsId = 10,
                            TagsId = 2
                        },
                        new
                        {
                            IngredientsId = 10,
                            TagsId = 1
                        },
                        new
                        {
                            IngredientsId = 10,
                            TagsId = 7
                        },
                        new
                        {
                            IngredientsId = 11,
                            TagsId = 3
                        },
                        new
                        {
                            IngredientsId = 11,
                            TagsId = 8
                        },
                        new
                        {
                            IngredientsId = 12,
                            TagsId = 3
                        },
                        new
                        {
                            IngredientsId = 12,
                            TagsId = 1
                        },
                        new
                        {
                            IngredientsId = 13,
                            TagsId = 5
                        },
                        new
                        {
                            IngredientsId = 13,
                            TagsId = 8
                        },
                        new
                        {
                            IngredientsId = 14,
                            TagsId = 2
                        },
                        new
                        {
                            IngredientsId = 14,
                            TagsId = 7
                        });
                });

            modelBuilder.Entity("MealTag", b =>
                {
                    b.Property<int>("MealsId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("MealsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("MealTag");

                    b.HasData(
                        new
                        {
                            MealsId = 1,
                            TagsId = 1
                        },
                        new
                        {
                            MealsId = 1,
                            TagsId = 2
                        },
                        new
                        {
                            MealsId = 1,
                            TagsId = 8
                        },
                        new
                        {
                            MealsId = 2,
                            TagsId = 1
                        },
                        new
                        {
                            MealsId = 2,
                            TagsId = 3
                        },
                        new
                        {
                            MealsId = 2,
                            TagsId = 8
                        },
                        new
                        {
                            MealsId = 3,
                            TagsId = 2
                        },
                        new
                        {
                            MealsId = 3,
                            TagsId = 5
                        },
                        new
                        {
                            MealsId = 4,
                            TagsId = 3
                        },
                        new
                        {
                            MealsId = 4,
                            TagsId = 6
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Vitalis.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Vitalis.Data.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("NutrientProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NutrientProfileId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://example.com/images/chicken-breast.jpg",
                            Name = "Chicken Breast",
                            Notes = "Lean protein source",
                            NutrientProfileId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://example.com/images/brown-rice.jpg",
                            Name = "Brown Rice",
                            Notes = "Whole grain carbohydrate",
                            NutrientProfileId = 2
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://example.com/images/broccoli.jpg",
                            Name = "Broccoli",
                            Notes = "Rich in fiber and vitamins",
                            NutrientProfileId = 3
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://example.com/images/olive-oil.jpg",
                            Name = "Olive Oil",
                            Notes = "Healthy fats",
                            NutrientProfileId = 4
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://example.com/images/eggs.jpg",
                            Name = "Eggs",
                            Notes = "High-quality protein and fats",
                            NutrientProfileId = 5
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://example.com/images/salmon.jpg",
                            Name = "Salmon",
                            Notes = "Rich in omega-3 fatty acids",
                            NutrientProfileId = 6
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://example.com/images/sweet-potato.jpg",
                            Name = "Sweet Potato",
                            Notes = "Complex carbs and fiber",
                            NutrientProfileId = 7
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://example.com/images/spinach.jpg",
                            Name = "Spinach",
                            Notes = "Iron-rich leafy green",
                            NutrientProfileId = 8
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "https://example.com/images/greek-yogurt.jpg",
                            Name = "Greek Yogurt",
                            Notes = "High in protein and probiotics",
                            NutrientProfileId = 9
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "https://example.com/images/quinoa.jpg",
                            Name = "Quinoa",
                            Notes = "Complete protein grain alternative",
                            NutrientProfileId = 10
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "https://example.com/images/avocado.jpg",
                            Name = "Avocado",
                            Notes = "Rich in healthy monounsaturated fats",
                            NutrientProfileId = 11
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "https://example.com/images/almonds.jpg",
                            Name = "Almonds",
                            Notes = "Nutrient-dense snack with healthy fats",
                            NutrientProfileId = 12
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "https://example.com/images/blueberries.jpg",
                            Name = "Blueberries",
                            Notes = "Antioxidant-rich fruit",
                            NutrientProfileId = 13
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "https://example.com/images/oats.jpg",
                            Name = "Oats",
                            Notes = "High in soluble fiber",
                            NutrientProfileId = 14
                        });
                });

            modelBuilder.Entity("Vitalis.Data.Models.JournalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("Vitalis.Data.Models.JournalEntryIngredient", b =>
                {
                    b.Property<int>("JournalEntryId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.HasKey("JournalEntryId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("JournalEntryIngredients");
                });

            modelBuilder.Entity("Vitalis.Data.Models.JournalEntryMeal", b =>
                {
                    b.Property<int>("JournalEntryId")
                        .HasColumnType("int");

                    b.Property<int>("MealId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("JournalEntryId", "MealId");

                    b.HasIndex("MealId");

                    b.ToTable("JournalEntryMeals");
                });

            modelBuilder.Entity("Vitalis.Data.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://example.com/images/meals/chicken-rice.jpg",
                            Name = "Grilled Chicken with Rice",
                            Notes = "High protein balanced meal"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://example.com/images/meals/salmon-sweetpotato.jpg",
                            Name = "Salmon with Sweet Potato",
                            Notes = "Rich in omega-3 and complex carbs"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://example.com/images/meals/oatmeal-blueberries.jpg",
                            Name = "Oatmeal with Blueberries",
                            Notes = "Great for breakfast"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://example.com/images/meals/avocado-yogurt.jpg",
                            Name = "Avocado Yogurt Bowl",
                            Notes = "Healthy fats and protein combo"
                        });
                });

            modelBuilder.Entity("Vitalis.Data.Models.MealIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("MealId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("MealId");

                    b.ToTable("MealIngredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IngredientId = 1,
                            MealId = 1,
                            Quantity = 200.0
                        },
                        new
                        {
                            Id = 2,
                            IngredientId = 2,
                            MealId = 1,
                            Quantity = 150.0
                        },
                        new
                        {
                            Id = 3,
                            IngredientId = 3,
                            MealId = 1,
                            Quantity = 100.0
                        },
                        new
                        {
                            Id = 4,
                            IngredientId = 6,
                            MealId = 2,
                            Quantity = 180.0
                        },
                        new
                        {
                            Id = 5,
                            IngredientId = 7,
                            MealId = 2,
                            Quantity = 200.0
                        },
                        new
                        {
                            Id = 6,
                            IngredientId = 8,
                            MealId = 2,
                            Quantity = 80.0
                        },
                        new
                        {
                            Id = 7,
                            IngredientId = 14,
                            MealId = 3,
                            Quantity = 100.0
                        },
                        new
                        {
                            Id = 8,
                            IngredientId = 13,
                            MealId = 3,
                            Quantity = 50.0
                        },
                        new
                        {
                            Id = 9,
                            IngredientId = 9,
                            MealId = 3,
                            Quantity = 150.0
                        },
                        new
                        {
                            Id = 10,
                            IngredientId = 11,
                            MealId = 4,
                            Quantity = 100.0
                        },
                        new
                        {
                            Id = 11,
                            IngredientId = 9,
                            MealId = 4,
                            Quantity = 150.0
                        },
                        new
                        {
                            Id = 12,
                            IngredientId = 12,
                            MealId = 4,
                            Quantity = 30.0
                        });
                });

            modelBuilder.Entity("Vitalis.Data.Models.NutrientProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Carbohydrates")
                        .HasColumnType("int");

                    b.Property<int>("Fat")
                        .HasColumnType("int");

                    b.Property<int>("Protein")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NutrientProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Carbohydrates = 0,
                            Fat = 4,
                            Protein = 31
                        },
                        new
                        {
                            Id = 2,
                            Carbohydrates = 23,
                            Fat = 1,
                            Protein = 3
                        },
                        new
                        {
                            Id = 3,
                            Carbohydrates = 7,
                            Fat = 0,
                            Protein = 3
                        },
                        new
                        {
                            Id = 4,
                            Carbohydrates = 0,
                            Fat = 100,
                            Protein = 0
                        },
                        new
                        {
                            Id = 5,
                            Carbohydrates = 1,
                            Fat = 11,
                            Protein = 13
                        },
                        new
                        {
                            Id = 6,
                            Carbohydrates = 0,
                            Fat = 13,
                            Protein = 20
                        },
                        new
                        {
                            Id = 7,
                            Carbohydrates = 20,
                            Fat = 0,
                            Protein = 2
                        },
                        new
                        {
                            Id = 8,
                            Carbohydrates = 4,
                            Fat = 0,
                            Protein = 3
                        },
                        new
                        {
                            Id = 9,
                            Carbohydrates = 4,
                            Fat = 5,
                            Protein = 10
                        },
                        new
                        {
                            Id = 10,
                            Carbohydrates = 21,
                            Fat = 2,
                            Protein = 4
                        },
                        new
                        {
                            Id = 11,
                            Carbohydrates = 9,
                            Fat = 15,
                            Protein = 2
                        },
                        new
                        {
                            Id = 12,
                            Carbohydrates = 22,
                            Fat = 49,
                            Protein = 21
                        },
                        new
                        {
                            Id = 13,
                            Carbohydrates = 14,
                            Fat = 0,
                            Protein = 1
                        },
                        new
                        {
                            Id = 14,
                            Carbohydrates = 66,
                            Fat = 7,
                            Protein = 17
                        });
                });

            modelBuilder.Entity("Vitalis.Data.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://example.com/images/tags/protein.png",
                            Name = "Protein"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://example.com/images/tags/carbs.png",
                            Name = "Carbs"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://example.com/images/tags/fats.png",
                            Name = "Fats"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://example.com/images/tags/vegetable.png",
                            Name = "Vegetable"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://example.com/images/tags/fruit.png",
                            Name = "Fruit"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://example.com/images/tags/dairy.png",
                            Name = "Dairy"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://example.com/images/tags/grain.png",
                            Name = "Grain"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://example.com/images/tags/healthy.png",
                            Name = "Healthy"
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "https://example.com/images/tags/meat.png",
                            Name = "Meat"
                        });
                });

            modelBuilder.Entity("IngredientTag", b =>
                {
                    b.HasOne("Vitalis.Data.Models.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vitalis.Data.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MealTag", b =>
                {
                    b.HasOne("Vitalis.Data.Models.Meal", null)
                        .WithMany()
                        .HasForeignKey("MealsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vitalis.Data.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Vitalis.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Vitalis.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vitalis.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Vitalis.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vitalis.Data.Models.Ingredient", b =>
                {
                    b.HasOne("Vitalis.Data.Models.NutrientProfile", "NutrientProfile")
                        .WithMany()
                        .HasForeignKey("NutrientProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NutrientProfile");
                });

            modelBuilder.Entity("Vitalis.Data.Models.JournalEntry", b =>
                {
                    b.HasOne("Vitalis.Data.Models.ApplicationUser", "User")
                        .WithOne("JournalEntry")
                        .HasForeignKey("Vitalis.Data.Models.JournalEntry", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vitalis.Data.Models.JournalEntryIngredient", b =>
                {
                    b.HasOne("Vitalis.Data.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vitalis.Data.Models.JournalEntry", "JournalEntry")
                        .WithMany("Ingredients")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("Vitalis.Data.Models.JournalEntryMeal", b =>
                {
                    b.HasOne("Vitalis.Data.Models.JournalEntry", "JournalEntry")
                        .WithMany("Meals")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vitalis.Data.Models.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JournalEntry");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("Vitalis.Data.Models.MealIngredient", b =>
                {
                    b.HasOne("Vitalis.Data.Models.Ingredient", "Ingredient")
                        .WithMany("Meals")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vitalis.Data.Models.Meal", "Meal")
                        .WithMany("Ingredients")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("Vitalis.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("Vitalis.Data.Models.Ingredient", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("Vitalis.Data.Models.JournalEntry", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Meals");
                });

            modelBuilder.Entity("Vitalis.Data.Models.Meal", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
